#!/usr/bin/env bash
# Install the Orbs publisher on this Mac (every 15 minutes).
#
# launchd cannot access Desktop/Documents (macOS privacy). The installed job
# runs from ~/.local/share/orbs-feed — a git clone outside protected folders.
# Re-run install after rotating IG tokens in ../orbs/.env.local.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ORBS_ENV="$(cd "$ROOT/../orbs" && pwd)/.env.local"
CONFIG_DIR="$HOME/.config/orbs"
PUBLISHER_ENV="$CONFIG_DIR/publisher.env"
PUBLISH_ROOT="$HOME/.local/share/orbs-feed"
REPO_URL="https://github.com/itis-ops/orbs-feed.git"
PLIST_ID="com.orbs.publisher"
PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_ID}.plist"
BIN_DIR="$HOME/bin"
LAUNCHER="$BIN_DIR/orbs-publisher"
SCRIPT="$ROOT/tools/local-publish.sh"
CRON_LINE="*/15 * * * * ${LAUNCHER} >> /tmp/orbs-publish-cron.log 2>&1"

chmod +x "$SCRIPT"
chmod +x "$ROOT/tools/trigger-publish.sh" 2>/dev/null || true

mkdir -p "$BIN_DIR" "$CONFIG_DIR"
if [[ ! -f "$ORBS_ENV" ]]; then
  echo "ERROR: missing $ORBS_ENV — create it with IG_USER_ID and IG_ACCESS_TOKEN first." >&2
  exit 1
fi
cp "$ORBS_ENV" "$PUBLISHER_ENV"
chmod 600 "$PUBLISHER_ENV"
echo "Synced credentials to $PUBLISHER_ENV (launchd cannot read Desktop paths)"

mkdir -p "$(dirname "$PUBLISH_ROOT")"
if [[ ! -d "$PUBLISH_ROOT/.git" ]]; then
  echo "Cloning orbs-feed to $PUBLISH_ROOT (outside Desktop for launchd)..."
  git clone "$REPO_URL" "$PUBLISH_ROOT"
else
  echo "Using publish clone at $PUBLISH_ROOT"
  git -C "$PUBLISH_ROOT" remote set-url origin "$REPO_URL" 2>/dev/null || true
fi

# Generated launcher lives outside protected folders so launchd can execute it.
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by orbs-feed/tools/install-scheduler.sh — do not edit.
# Re-run install-scheduler.sh after moving the repo.
set -euo pipefail

ROOT="${PUBLISH_ROOT}"
PUBLISHER_ENV="${PUBLISHER_ENV}"
LOG="/tmp/orbs-publish.log"
LOCKDIR="/tmp/com.orbs.publisher.lockdir"
NODE="\$(command -v node)"

ts() { date "+%Y-%m-%d %H:%M:%S"; }
log() { echo "[\$(ts)] \$*" >> "\$LOG"; }

if [[ -f "\$LOG" ]] && [[ "\$(wc -l < "\$LOG" | tr -d ' ')" -gt 800 ]]; then
  tail -400 "\$LOG" > "\${LOG}.tmp" && mv "\${LOG}.tmp" "\$LOG"
fi

if ! mkdir "\$LOCKDIR" 2>/dev/null; then
  log "skip: another publish run in progress"
  exit 0
fi
trap 'rmdir "\$LOCKDIR" 2>/dev/null || true' EXIT

if [[ ! -f "\$PUBLISHER_ENV" ]]; then
  log "ERROR: missing \$PUBLISHER_ENV — run tools/install-scheduler.sh"
  exit 1
fi

if [[ -z "\$NODE" ]]; then
  log "ERROR: node not found in PATH"
  exit 1
fi

unset GRAPH_BASE
while IFS= read -r line || [[ -n "\$line" ]]; do
  line="\${line%%#*}"
  line="\$(echo "\$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*\$//')"
  [[ -z "\$line" || "\$line" != *=* ]] && continue
  export "\$line"
done < "\$PUBLISHER_ENV"

if [[ -z "\${IG_USER_ID:-}" || -z "\${IG_ACCESS_TOKEN:-}" ]]; then
  log "ERROR: IG_USER_ID or IG_ACCESS_TOKEN missing in \$PUBLISHER_ENV"
  exit 1
fi

cd "\$ROOT"

log "start publish run"

if ! git pull --ff-only origin main >> "\$LOG" 2>&1; then
  log "WARN: git pull failed — continuing with local queue.json"
fi

set +e
output=\$("\$NODE" tools/publish-due.mjs 2>&1)
exit_code=\$?
set -e

while IFS= read -r line; do log "\$line"; done <<< "\$output"

if [[ \$exit_code -ne 0 ]]; then
  log "ERROR: publish-due.mjs exited \$exit_code"
  exit "\$exit_code"
fi

if [[ -n "\$(git status --porcelain queue.json)" ]]; then
  git add queue.json
  git commit -m "publish: update queue state [skip ci]" >> "\$LOG" 2>&1
  if git push origin main >> "\$LOG" 2>&1; then
    log "queue.json pushed to origin/main"
  else
    log "ERROR: git push failed — queue updated locally but not on GitHub"
    exit 1
  fi
else
  log "no queue changes"
fi

log "done"
exit 0
EOF

chmod +x "$LAUNCHER"

install_launchd() {
  if ! mkdir -p "$HOME/Library/LaunchAgents" 2>/dev/null; then
    return 1
  fi
  if [[ ! -w "$HOME/Library/LaunchAgents" ]]; then
    return 1
  fi

  cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_ID}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${LAUNCHER}</string>
  </array>
  <key>StartInterval</key>
  <integer>900</integer>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/tmp/orbs-publish-launchd.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/orbs-publish-launchd.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>${BIN_DIR}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
EOF

  launchctl bootout "gui/$(id -u)/${PLIST_ID}" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH"
  launchctl enable "gui/$(id -u)/${PLIST_ID}"
  launchctl kickstart -k "gui/$(id -u)/${PLIST_ID}"

  echo "Installed via launchd: ${PLIST_ID}"
  echo "  Runs: every 15 minutes (+ once now)"
  echo "  Launcher: ${LAUNCHER}"
  echo "  Plist: ${PLIST_PATH}"
  return 0
}

install_crontab() {
  (crontab -l 2>/dev/null \
    | grep -v 'orbs-feed/tools/local-publish' \
    | grep -v 'orbs-publisher' \
    | grep -v 'orbs-feed/tools/trigger-publish' \
    || true; echo "$CRON_LINE") | crontab -
  echo "Installed via user crontab (~/Library/LaunchAgents is not writable on this Mac)"
  echo "  Runs: every 15 minutes"
  echo "  Launcher: ${LAUNCHER}"
  echo "  Cron log: /tmp/orbs-publish-cron.log"
  echo ""
  echo "Optional — fix launchd path for cleaner scheduling:"
  echo "  sudo chown -R $(whoami) ~/Library/LaunchAgents"
  echo "  bash tools/install-scheduler.sh"
}

if install_launchd; then
  :
else
  echo "launchd unavailable — installing crontab fallback..." >&2
  install_crontab
fi

echo ""
echo "  Dev repo:     ${ROOT}"
echo "  Publish clone: ${PUBLISH_ROOT}"
echo "  Log:          /tmp/orbs-publish.log"
echo ""
echo "Verify: tail -f /tmp/orbs-publish.log"
echo "Run once now: ${LAUNCHER}"

"$LAUNCHER" || true
